---
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        Enabled: false
      Layout/ClosingParenthesisIndentation:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Layout/FirstHashElementIndentation:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Layout/MultilineMethodCallBraceLayout:
        Enabled: false
      Style/StringLiterals:
        Enabled: false
      Style/TrailingCommaInHashLiteral:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        # TODO: enable this linter
        Enabled: false
      Style/HashSyntax:
        Enabled: false
