name: Environment variables on Gollum
on: gollum
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: Display Environment Info
      run: |
        echo "Runner Machine Name : $(hostname)"
        echo "Operating System: $(uname)"
        echo "Commit SHA: $GITHUB_SHA"
        echo "Git Ref: $GITHUB_REF"